defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: EP1001 Blog
subtitle: Further Digital Fab & Prototyping Fundamentals
baseurl: "/EP1001"  # the subpath of your site, e.g. /blog
# theme: panthera-jekyll
remote-theme: christianezeani/panthera-jekyll

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: About Me
    link: /about.html
    icon: ""

  - text: Fablab Safety
    link: /docs/safety.html
    icon: ""

  - text: Final Project
    link: /docs/final_project.html
    icon: ""

  - text: Contact
    link: /contact.html
    icon: ""


# Socialmedia Icons
social_icons:
  - name: linkedin
    link: ""
    icon: fab fa-linkedin

  - name: github
    link: ""
    icon: fab fa-github-square

  - name: facebook
    link: ""
    icon: fab fa-facebook-square

  - name: twitter
    link: ""
    icon: fab fa-twitter
