defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: EP1000 Blog
subtitle: Digital Fab & Prototyping Fundamentals
baseurl: "/EP1000_"  # the subpath of your site, e.g. /blog
# theme: panthera-jekyll
remote-theme: christianezeani/panthera-jekyll

# Side Menu Links
menu:
  - text: Home
    link: /
    icon: ""

  - text: About Me
    link: /about.html
    icon: ""

  - text: Fablab Safety
    link: /docs/safety.html
    icon: ""

  - text: Prototyping
    link: /docs/prototyping.html
    icon: ""

  - text: Project Management
    link: /docs/proj-mgmt.html
    icon: ""

  - text: Web Development
    link: /docs/web.html
    icon: ""

  - text: GitHub & Version Control
    link: /docs/versioncontrol.html
    icon: ""

  - text: Computer Graphics
    link: /docs/comgraphics.html
    icon: ""

  - text: Computer Aided Design
    link: /docs/cad.html
    icon: ""

  - text: 3D Modelling
    link: /docs/3dmodel.html
    icon: ""

  - text: 3D Printing
    link: /docs/3dprint.html
    icon: ""

  - text: Final Project
    link: /docs/project.html
    icon: ""

  - text: Contact
    link: /contact.html
    icon: ""


# Socialmedia Icons
social_icons:
  - name: linkedin
    link: ""
    icon: fab fa-linkedin

  - name: github
    link: ""
    icon: fab fa-github-square

  - name: facebook
    link: ""
    icon: fab fa-facebook-square

  - name: twitter
    link: ""
    icon: fab fa-twitter
